[font]
size = 13
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }


[keyboard]
bindings = [
	# Make Ctrl+Backspace delete an entire word
	{ key = "Back", mods = "Control", chars = "\u0017" }
]
